-- 코드를 입력하세요
SELECT I.ANIMAL_ID, I.NAME
FROM ANIMAL_INS I
WHERE I.DATETIME > (SELECT O.DATETIME
                 FROM ANIMAL_OUTS O
                 WHERE I.ANIMAL_ID = O.ANIMAL_ID)
ORDER BY I.DATETIME