-- 코드를 입력하세요
SELECT MONTH(START_DATE), CAR_ID, COUNT(HISTORY_ID) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE start_date>="2022-08-01" and start_date<"2022-11-01" AND CAR_ID IN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE start_date>="2022-08-01" and start_date<"2022-11-01"
    GROUP BY CAR_ID
    HAVING COUNT(HISTORY_ID) >= 5
    )
GROUP BY MONTH(START_DATE), CAR_ID
HAVING RECORDS > 0
ORDER BY MONTH(START_DATE), CAR_ID DESC